language: c++
dist: bionic
compiler: clang
addons:
  apt:
    packages:
      - "libsdl2-dev"
      - "python3"
      - "python3-pip"
before_install:
- pyenv global system 3.6.7
- sudo pip3 install conan meson
script:
- cd conan
- ./install.sh