language: c++
dist: bionic
compiler: clang
before_install:
- pyenv install 3.7.0
- pyenv global system 3.7.0
- sudo apt-get install -y libsdl2-dev python3
- sudo pip install conan meson
script:
- cd conan
- ./install.sh