language: c++
dist: bionic
compiler: clang
before_install:
- pyenv global system 3.6.7
- sudo apt-get install -y python3 python3-pip python3-setuptools ninja-build libsdl2-dev
- pip3 install conan meson
script:
- cd conan
- ./install.sh
- cd ../build
- DESTDIR=${TRAVIS_BUILD_DIR}/install
- sudo ninja install