language: c++
dist: bionic
compiler: clang
before_install:
- pyenv global system 3.6.7
- sudo apt-get install -y libsdl2-dev python3 python3-pip python3-setuptools libboost-dev
- pip3 install conan meson
script:
- cd conan
- ./install.sh